language: python
python:
  - "3.6"      # current default Python on Travis CI
   
services:
  - docker

before_install:
  - docker pull pascal0x90/basic_phuzzer
#  - pip install travis-wait-improved

script: 
  - ./run.sh chall.bin
